### ISSUE TITLE
FAIL disconnecting Invalid roomId

### ISSUE THREAD

**Issue by pp3times** [spatialdj/backend#2]
![image](https://user-images.githubusercontent.com/73677600/159055485-5db6e5b9-7ea8-41f8-b8fb-f91624ae3838.png)

I got FAIL disconnecting Invalid roomId when try to create room

![image](https://user-images.githubusercontent.com/73677600/159055653-96bbc3e7-5e4c-4aca-898a-e61fd10c9a91.png)

**Comment by pp3times** [comment]
I fixed it now thanks

**Comment by KevinLu** [comment]
Can you provide some description on how you fixed it so others with the same issue can learn? thanks

**Comment by pp3times** [comment]
Oh sure, I just try to reinstall dependencies from yarn to npm it work for me. 😃

**Comment by pp3times** [comment]
But I need to know how to deploy this project can you tell me about that?

**Comment by KevinLu** [comment]
> But I need to know how to deploy this project can you tell me about that?

For our demo site, we used Google Cloud Platform to host the project. You can follow the steps here: https://github.com/spatialdj/backend#running-in-production to deploy it.
